language: go
services:
  - docker
jobs:
  include:
    - stage: test
      install:
        - go get github.com/golang/lint/golint
        - go get github.com/golang/dep/cmd/dep
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
      before_script:
        - dep ensure
      script:
        - golint -set_exit_status $(go list ./...)
        - go vet -v ./...
        - go build -v ./...
        - go test -v ./...
        - goveralls -service=travis-ci
        - go test -race -coverprofile=coverage.txt -covermode=atomic
        - bash <(curl -s https://codecov.io/bash)

    - stage: build
      script: docker build -t test/app .
