version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - run: go get github.com/golang/lint/golint
      #- run: go get github.com/golang/dep/cmd/dep
      - checkout
      - run: dep ensure
      - run: golint -set_exit_status $(go list ./...)
      - run: go vet -v ./...
      - run: go build -v ./...
      - run: go test -v ./...
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)
      - run: docker build -t test/app .
